jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.AWS_SECRET_KEY }}" > private_key
          chmod 600 private_key

      - name: Connect to EC2 and run commands
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} "echo 'Hello from EC2!'"
